development:
  adapter: postgresql
  encoding: unicode
  database: korytegman_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: korytegman_test
  pool: 5
  
test:
    adapter: postgresql
    encoding: unicode
    database: korytegman_test
    pool: 5