development:
  adapter: postgresql
  encoding: unicode
  database: korytegman_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: korytegman_test
  pool: 5
  
production:
    adapter: postgresql
    encoding: unicode
    database: korytegman_production
    pool: 5